edition: 1.0.0
name: mofei_tools
access: default
vars:
  region: cn-hangzhou
services:
  tools-front_end:
    component: devsapp/fc
    actions: # 自定义执行逻辑
      pre-deploy: # 在deploy之前运行
        - run: npm run build
          path: ./ # 命令行运行的路径
        - run: s build --use-docker --dockerfile ./Dockerfile
          path: ./ # 命令行运行的路径
        #
    props:
      region: ${vars.region}
      service:
        name: mofei_tools
        description: This is FC service
        internetAccess: true
        logConfig: auto
      function:
        name: mofei_tools
        handler: index.handler
        timeout: 120
        memorySize: 1024
        runtime: custom-container
        customContainerConfig:
          image: registry.cn-hangzhou.aliyuncs.com/zhuwenlong_com/tools:v1.0 # 需要换成自己的registry地址
          accelerationType: Default
        instanceConcurrency: 100
        codeUri: ./
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - serviceName: zhuwenlong_com_frontend
              functionName: zhuwenlong_com_frontend
              path: /*
